---
title: "poisson_regression"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
olympics = read.csv("01_data_preprocessing/data/olympics.csv")
```

```{r}
par(mfrow=c(2,3))
hist(olympics$Total[olympics$Country == 1], 
     main = "USA", xlab = "Total medals", col = "blue", breaks = 20)
hist(olympics$Total[olympics$Country == 2], 
     main = "CHN", xlab = "Total medals", col = "red", breaks = 20)
hist(olympics$Total[olympics$Country == 3], 
     main = "JPN", xlab = "Total medals", col = "green", breaks = 20)
hist(olympics$Total[olympics$Country == 4], 
     main = "AUS", xlab = "Total medals", col = "orange", breaks = 20)
hist(olympics$Total[olympics$Country == 5], 
     main = "FRA", xlab = "Total medals", col = "purple", breaks = 20)
```

```{r}
# Poisson regression for USA
usa_model = glm(Total~X.Athletes+X.Events+IsHost+Year, data=olympics[olympics$Country == 1,], family=poisson(link="log"))
# Poisson regression for CHN
chn_model = glm(Total~X.Athletes+X.Events+IsHost+Year, data=olympics[olympics$Country == 2,], family=poisson(link="log"))
# Poisson regression for JPN
jpn_model = glm(Total~X.Athletes+X.Events+IsHost+Year, data=olympics[olympics$Country == 3,], family=poisson(link="log"))
# Poisson regression for AUS
aus_model = glm(Total~X.Athletes+X.Events+IsHost+Year, data=olympics[olympics$Country == 4,], family=poisson(link="log"))
# Poisson regression for FRA
fra_model = glm(Total~X.Athletes+X.Events+IsHost+Year, data=olympics[olympics$Country == 5,], family=poisson(link="log"))

# Plot the curve using plot
par(mfrow=c(2,3))
plot(usa_model$fitted.values, main="USA Poisson Regression", xlab="Index", ylab="Fitted Values", col="blue")
plot(chn_model$fitted.values, main="CHN Poisson Regression", xlab="Index", ylab="Fitted Values", col="red")
plot(jpn_model$fitted.values, main="JPN Poisson Regression", xlab="Index", ylab="Fitted Values", col="green")
plot(aus_model$fitted.values, main="AUS Poisson Regression", xlab="Index", ylab="Fitted Values", col="orange")
plot(fra_model$fitted.values, main="FRA Poisson Regression", xlab="Index", ylab="Fitted Values", col="purple")
```

```{r}
# R2 of the models
usa_r2 = 1 - (usa_model$deviance / usa_model$null.deviance)
chn_r2 = 1 - (chn_model$deviance / chn_model$null.deviance)
jpn_r2 = 1 - (jpn_model$deviance / jpn_model$null.deviance)
aus_r2 = 1 - (aus_model$deviance / aus_model$null.deviance)
fra_r2 = 1 - (fra_model$deviance / fra_model$null.deviance)
r2_values = data.frame(Country = c("USA", "CHN", "JPN", "AUS", "FRA"), R2 = c(usa_r2, chn_r2, jpn_r2, aus_r2, fra_r2))
print(r2_values)
```